class AfterEffectsTemplateService {
  generateTemplate(effects, videoMetadata = {}) {
    const template = {
      version: "1.0",
      projectName: `Video_Effects_${Date.now()}`,
      composition: {
        name: "Main_Composition",
        width: videoMetadata.width || 1920,
        height: videoMetadata.height || 1080,
        frameRate: videoMetadata.frameRate || 30,
        duration: videoMetadata.duration || 30
      },
      effects: effects.map(effect => this.convertEffectToAEFormat(effect)),
      script: this.generateJSXScript(effects, videoMetadata)
    };

    return template;
  }

  convertEffectToAEFormat(effect) {
    const aeEffect = {
      name: effect.name,
      type: effect.type,
      startTime: effect.timestamp,
      duration: effect.duration,
      parameters: {}
    };

    switch (effect.type.toLowerCase()) {
      case 'zoom':
        aeEffect.parameters = {
          property: 'Scale',
          keyframes: [
            { time: effect.timestamp, value: [effect.parameters?.scaleStart || 100, effect.parameters?.scaleStart || 100] },
            { time: effect.timestamp + effect.duration, value: [effect.parameters?.scaleEnd || 120, effect.parameters?.scaleEnd || 120] }
          ],
          easing: effect.parameters?.easing || 'easeInOut'
        };
        break;

      case 'pan':
        aeEffect.parameters = {
          property: 'Position',
          keyframes: [
            { time: effect.timestamp, value: [960, 540] },
            { time: effect.timestamp + effect.duration, value: [1200, 540] }
          ]
        };
        break;

      case 'blur':
        aeEffect.parameters = {
          effect: 'Gaussian Blur',
          property: 'Blurriness',
          keyframes: [
            { time: effect.timestamp, value: 0 },
            { time: effect.timestamp + effect.duration / 2, value: effect.parameters?.blurAmount || 20 },
            { time: effect.timestamp + effect.duration, value: 0 }
          ]
        };
        break;

      case 'glow':
        aeEffect.parameters = {
          effect: 'Glow',
          properties: {
            'Glow Threshold': 50,
            'Glow Radius': effect.parameters?.glowRadius || 20,
            'Glow Intensity': effect.parameters?.glowIntensity || 1.5
          }
        };
        break;

      case 'shake':
        aeEffect.parameters = {
          expression: 'wiggle',
          frequency: effect.parameters?.frequency || 10,
          amplitude: effect.parameters?.amplitude || 5
        };
        break;

      case 'text':
        aeEffect.parameters = {
          type: 'text',
          animationType: effect.parameters?.animationType || 'typewriter',
          speed: effect.parameters?.speed || 0.05
        };
        break;
    }

    return aeEffect;
  }

  generateJSXScript(effects, videoMetadata) {
    const script = `// After Effects Script - Generated by AI Video Effects Analyzer
// Project: Video_Effects_${Date.now()}

(function() {
    app.beginUndoGroup("Apply Video Effects");
    
    // Create composition
    var comp = app.project.items.addComp(
        "Main_Composition",
        ${videoMetadata.width || 1920},
        ${videoMetadata.height || 1080},
        1.0,
        ${videoMetadata.duration || 30},
        ${videoMetadata.frameRate || 30}
    );
    
    // Import video (user needs to select)
    var videoFile = File.openDialog("Select your video file");
    if (videoFile) {
        var footage = app.project.importFile(new ImportOptions(videoFile));
        var videoLayer = comp.layers.add(footage);
        
        ${effects.map((effect, index) => this.generateEffectScript(effect, index)).join('\n        ')}
    }
    
    app.endUndoGroup();
    alert("Effects applied successfully!");
})();`;

    return script;
  }

  generateEffectScript(effect, index) {
    switch (effect.type.toLowerCase()) {
      case 'zoom':
        return `
// Effect ${index + 1}: ${effect.name}
var scaleProperty = videoLayer.property("Transform").property("Scale");
scaleProperty.setValueAtTime(${effect.timestamp}, [${effect.parameters?.scaleStart || 100}, ${effect.parameters?.scaleStart || 100}]);
scaleProperty.setValueAtTime(${effect.timestamp + effect.duration}, [${effect.parameters?.scaleEnd || 120}, ${effect.parameters?.scaleEnd || 120}]);
scaleProperty.setInterpolationTypeAtKey(1, KeyframeInterpolationType.BEZIER);
scaleProperty.setInterpolationTypeAtKey(2, KeyframeInterpolationType.BEZIER);`;

      case 'pan':
        return `
// Effect ${index + 1}: ${effect.name}
var posProperty = videoLayer.property("Transform").property("Position");
posProperty.setValueAtTime(${effect.timestamp}, [960, 540]);
posProperty.setValueAtTime(${effect.timestamp + effect.duration}, [1200, 540]);`;

      case 'blur':
        return `
// Effect ${index + 1}: ${effect.name}
var blurEffect = videoLayer.property("Effects").addProperty("Gaussian Blur");
var blurProperty = blurEffect.property("Blurriness");
blurProperty.setValueAtTime(${effect.timestamp}, 0);
blurProperty.setValueAtTime(${effect.timestamp + effect.duration / 2}, ${effect.parameters?.blurAmount || 20});
blurProperty.setValueAtTime(${effect.timestamp + effect.duration}, 0);`;

      case 'glow':
        return `
// Effect ${index + 1}: ${effect.name}
var glowEffect = videoLayer.property("Effects").addProperty("Glow");
glowEffect.property("Glow Threshold").setValue(50);
glowEffect.property("Glow Radius").setValue(${effect.parameters?.glowRadius || 20});
glowEffect.property("Glow Intensity").setValue(${effect.parameters?.glowIntensity || 1.5});`;

      case 'shake':
        return `
// Effect ${index + 1}: ${effect.name}
var posProperty = videoLayer.property("Transform").property("Position");
posProperty.expression = "wiggle(${effect.parameters?.frequency || 10}, ${effect.parameters?.amplitude || 5})";`;

      default:
        return `// Effect ${index + 1}: ${effect.name} (manual setup required)`;
    }
  }

  downloadTemplate(template, filename = 'ae_template') {
    const jsxContent = template.script;
    const jsonContent = JSON.stringify({
      version: template.version,
      projectName: template.projectName,
      composition: template.composition,
      effects: template.effects
    }, null, 2);

    this.downloadFile(jsxContent, `${filename}.jsx`, 'text/plain');
    this.downloadFile(jsonContent, `${filename}_metadata.json`, 'application/json');
  }

  downloadFile(content, filename, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

export default new AfterEffectsTemplateService();
